resolver: lts-10.0
packages:
- .
- location:
    git: https://github.com/odr/tracy.git
    commit: 84444f9728ab168b8d9512aafa5a32612b5e471d
  extra-dep: true
extra-deps:
- xeno-0.3.4
# - tracy-0.1.4.0
